version: '2.3'

# create default network
#networks:
#  default:
#    external:
#      name: ros-network

volumes:
  workspace:

services:

  micro-ROS-agent:
    image: microros/micro-ros-agent:humble
    container_name: ros2_micro_ros_agent_humble
    init: true
    restart: unless-stopped
    privileged: true
    network_mode: host
    devices:
      - "/dev:/dev"
    volumes:
      - "/dev:/dev"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - ROS_DOMAIN_ID=50
    #command: serial --dev /dev/ttyUSB0 -v6
    command: udp4 --port 8888

  ros2:
    build: ./image
    image: wn1980/ros2-humble${TAG}
    container_name: ros2_humble
    init: true
    restart: unless-stopped
    privileged: true
    network_mode: host
    devices:
      - "/dev:/dev"
    volumes:
      - "/dev:/dev"
      - "/run/systemd:/run/systemd"
      - "/etc/localtime:/etc/localtime:ro"
      - "workspace:/workspace"
      - "~/.gitconfig:/home/developer/.gitconfig"
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X9"]
      interval: "1m"
      retries: 20
    environment:
      - ROS_DOMAIN_ID=50
    #cpus: 4
    #ports:
    #  - "8559:8008"
    #  - "9902:6901"
